import { UniEditorElementOptions, UniEditorElementInsertImageOptions, UniEditorElementInsertTextOptions, UniEditorElementInsertMentionOptions, UniEditorElementGetSelectionTextOptions, UniEditorElementSetContentsOptions, CreateEditorContextAsync, EditorContext, UniEditorElementGetContentsOptions, IUniEditorElement, UniEditorElementInsertLinkOptions, } from '../interface.uts'

export { UniEditorElementOptions, UniEditorElementInsertImageOptions, UniEditorElementInsertTextOptions, UniEditorElementInsertMentionOptions, UniEditorElementGetSelectionTextOptions, UniEditorElementSetContentsOptions, CreateEditorContextAsync, EditorContext, UniEditorElementGetContentsOptions, IUniEditorElement, UniEditorElementInsertLinkOptions, }

function createEditorEventName(name : string, id : string) {
  return `__UNIEDITOR_${name}_${id}`
}

let callbackId = 100000

function LOG(...args : string[]) {
  // 此处供开发时调试
  // console.log(`${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()} [Editor LOG]`, ...args)
}

function generateCallbackId() : number {
  return ++callbackId
}

export class NativeEditor {
  id : string
  private pendingCallbacks = new Map<number, any | null>()
  private disposed = false

  constructor(id : string, element : UniEditorElement) {
    this.id = id

    element.setNativeEditor(this)

    uni.$on(createEditorEventName('callback', this.id), (cbId : number, result : any) => {
      this.handleCallback(cbId, result)
    })
  }

  registerCallback(cbId : number, options : any | null) {
    if (this.disposed) {
      return
    }
    this.pendingCallbacks.set(cbId, options)
  }

  private handleCallback(cbId : number, result : any) {
    const callbacks = this.pendingCallbacks.get(cbId)

    // 移除回调
    this.pendingCallbacks.delete(cbId)

    if (callbacks == null) {
      LOG('Callback not found for id:', cbId.toString())
      return
    }

    const errMsg = result['errMsg'] as string | null
    const isSuccess = errMsg != null && errMsg.indexOf(':ok') > -1

    // 调用相应的回调函数
    if (isSuccess) {
      const success = callbacks['success'] as ((res : any) => void) | null
      if (success != null) {
        success(result)
      }
    } else {
      const fail = callbacks['fail'] as ((res : any) => void) | null
      if (fail != null) {
        fail(result)
      }
    }

    // 总是调用 complete
    const complete = callbacks['complete'] as ((res : any) => void) | null
    if (complete != null) {
      complete(result)
    }
  }

  dispose() {
    if (this.disposed) {
      return
    }
    this.disposed = true
    this.pendingCallbacks.clear()
    uni.$off(createEditorEventName('callback', this.id))
  }
}

export class UniEditorElement extends UniViewElementImpl implements IUniEditorElement {
  override tagName : string = 'EDITOR'
  override nodeName : string = 'EDITOR'

  private nativeEditor : NativeEditor | null = null

  // @ts-ignore dispose
  override dispose() {
    this.nativeEditor?.dispose()
    this.nativeEditor = null
  }

  private getNativeEditorId() : string {
    return this.nativeEditor!.id
  }

  setNativeEditor(nativeEditor : NativeEditor) {
    this.nativeEditor = nativeEditor
  }

  format(name : string, value : string | number | null = null) : void {
    uni.$emit(createEditorEventName('format', this.getNativeEditorId()), name, value)
  }

  insertDivider(options : UniEditorElementOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('insertDivider', this.getNativeEditorId()), options, cbId)
  }

  insertImage(options : UniEditorElementInsertImageOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('insertImage', this.getNativeEditorId()), options, cbId)
  }

  insertText(options : UniEditorElementInsertTextOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('insertText', this.getNativeEditorId()), options, cbId)
  }

  insertLink(options : UniEditorElementInsertLinkOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('insertLink', this.getNativeEditorId()), options, cbId)
  }

  insertMention(options : UniEditorElementInsertMentionOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('insertMention', this.getNativeEditorId()), options, cbId)
  }

  setContents(options : UniEditorElementSetContentsOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('setContents', this.getNativeEditorId()), options, cbId)
  }

  getContents(options : UniEditorElementGetContentsOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('getContents', this.getNativeEditorId()), options, cbId)
  }

  clear(options : UniEditorElementOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('clear', this.getNativeEditorId()), options, cbId)
  }

  removeFormat(options : UniEditorElementOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('removeFormat', this.getNativeEditorId()), options, cbId)
  }

  undo(options : UniEditorElementOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('undo', this.getNativeEditorId()), options, cbId)
  }

  redo(options : UniEditorElementOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('redo', this.getNativeEditorId()), options, cbId)
  }

  /**
   * TODO 和基类冲突，不支持 success 等回调
   */
  override blur() : void {
    uni.$emit(createEditorEventName('blur', this.getNativeEditorId()))
  }

  getSelectionText(options : UniEditorElementGetSelectionTextOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('getSelectionText', this.getNativeEditorId()), options, cbId)
  }

  scrollIntoView(options : UniEditorElementOptions | null) : void {
    const cbId = generateCallbackId()
    this.nativeEditor?.registerCallback(cbId, options)
    uni.$emit(createEditorEventName('scrollIntoView', this.getNativeEditorId()), options, cbId)
  }
}

export const createEditorContextAsync : CreateEditorContextAsync = (options) : void => {
  const id = options.id
  const component = options.component
  const success = options.success
  const fail = options.fail
  const complete = options.complete

  let editorElement : UniEditorElement | null = null;
  if (component == null) {
    const pages = getCurrentPages();
    if (pages.length > 0) {
      // #ifdef APP-ANDROID
      // 安卓上 $el.parentElement 拿到的是一个空对象
      editorElement = pages[pages.length - 1].$vm!.$el?.querySelector('#' + id) as UniEditorElement | null;
      // #endif

      // #ifndef APP-ANDROID
      editorElement = pages[pages.length - 1].$vm!.$el?.parentElement?.querySelector('#' + id) as UniEditorElement | null;
      // #endif
    }
  } else {
    editorElement = component.$el?.parentElement?.querySelector('#' + id) as UniEditorElement | null;
  }
  if (editorElement == null) {
    const uniError = new UniError('uni-createEditorContextAsync', -1, 'editor id or component invalid.')
    fail?.(uniError)
    complete?.()
  } else {
    success?.(new EditorContextImpl(editorElement))
    complete?.()
  }
}

class EditorContextImpl implements EditorContext {

  constructor(private editorElement : UniEditorElement) {
  }

  format(name : string, value : string | number | null) : void {
    this.editorElement.format(name, value)
  }

  insertDivider(options ?: UniEditorElementOptions | null) : void {
    this.editorElement.insertDivider(options)
  }

  insertImage(options ?: UniEditorElementInsertImageOptions | null) : void {
    this.editorElement.insertImage(options)
  }

  insertText(options ?: UniEditorElementInsertTextOptions | null) : void {
    this.editorElement.insertText(options)
  }

  insertLink(options ?: UniEditorElementInsertLinkOptions | null) : void {
    this.editorElement.insertLink(options)
  }

  insertMention(options ?: UniEditorElementInsertMentionOptions | null) : void {
    this.editorElement.insertMention(options)
  }

  setContents(options ?: UniEditorElementSetContentsOptions | null) : void {
    this.editorElement.setContents(options)
  }

  getContents(options ?: UniEditorElementGetContentsOptions | null) : void {
    this.editorElement.getContents(options)
  }

  getSelectionText(options ?: UniEditorElementGetSelectionTextOptions | null) : void {
    this.editorElement.getSelectionText(options)
  }

  clear(options ?: UniEditorElementOptions | null) : void {
    this.editorElement.clear(options)
  }

  removeFormat(options ?: UniEditorElementOptions | null) : void {
    this.editorElement.removeFormat(options)
  }

  undo(options ?: UniEditorElementOptions | null) : void {
    this.editorElement.undo(options)
  }

  redo(options ?: UniEditorElementOptions | null) : void {
    this.editorElement.redo(options)
  }

  blur(options ?: UniEditorElementOptions | null) : void {
    this.editorElement.blur()
    options?.success?.({ errMsg: 'blur:ok' })
    options?.complete?.({ errMsg: 'blur:ok' })
  }

  scrollIntoView(options ?: UniEditorElementOptions | null) : void {
    this.editorElement.scrollIntoView(options)
  }
}
