export default [
  'scanCode',
  'setScreenBrightness',
  'getScreenBrightness',
  'setKeepScreenOn',
  'addPhoneContact',
  'subscribePush',
  'unsubscribePush',
  'onPush',
  'offPush',
  'saveImageToPhotosAlbum',
  'saveVideoToPhotosAlbum',
  'setClipboardData',
  'getClipboardData',
  'getRecorderManager',
  'login',
  'share',
  'requestPayment'
]
