export * from './jsonFile'
export { AppJson, ComponentJson, MiniProgramComponentsType } from './types'
export { mergeMiniProgramAppJson, parseMiniProgramPagesJson } from './pages'
export { parseMiniProgramProjectJson } from './project'
export { parseIndependentSubPackages } from './subpackage'
export type { IndependentSubPackage } from './subpackage'
