packages:
  - 'packages/*'
  - 'packages/playground/*'
  - 'packages/uni-cli-utils/__tests__/examples/easycom'
catalog:
  '@amap/amap-jsapi-types': 0.0.8
  '@babel/code-frame': 7.24.7
  '@babel/generator': 7.25.6
  '@babel/core': 7.25.2
  '@babel/parser': 7.25.6
  '@babel/types': 7.25.6
  '@dcloudio/types': 3.4.15
  '@dcloudio/uni-app-x': 0.7.60
  '@rollup/pluginutils': 5.1.0
  '@types/adm-zip': 0.5.5
  '@types/debug': 4.1.12
  '@types/estree': 1.0.5
  '@types/google.maps': 3.58.0
  '@types/fs-extra': 9.0.13
  '@types/mime': 2.0.3
  '@types/module-alias': 2.0.4
  '@types/pako': 1.0.2
  '@types/resolve': 1.20.6
  '@types/sass': 1.43.1
  '@vitejs/plugin-legacy': 5.3.2
  '@vitejs/plugin-vue': 5.1.0
  '@vitejs/plugin-vue-jsx': 3.1.0
  '@vue/compiler-core': 3.4.21
  '@vue/compiler-dom': 3.4.21
  '@vue/compiler-sfc': 3.4.21
  '@vue/compiler-ssr': 3.4.21
  '@vue/consolidate': 1.0.0
  '@vue/reactivity': 3.4.21
  '@vue/runtime-core': 3.4.21
  '@vue/runtime-dom': 3.4.21
  '@vue/shared': 3.4.21
  '@vue/server-renderer': 3.4.21
  'adm-zip': 0.5.16
  'autoprefixer': 10.4.20
  'chokidar': 3.6.0
  'cypress': 10.11.0
  'debug': 4.3.7
  'semver': 7.6.3
  'esbuild': 0.20.2
  'isbinaryfile': 5.0.2
  'es-module-lexer': 1.5.4
  'estree-walker': 2.0.2
  'express': 4.20.0
  'fast-glob': 3.3.3
  'fs-extra': 10.1.0
  'hash-sum': 2.0.0
  'jimp': 0.10.3
  'jsonc-parser': 3.3.1
  'licia': 1.41.1
  'magic-string': 0.30.11
  'merge': 2.1.1
  'mime': 3.0.0
  'minimatch': 9.0.5
  'module-alias': 2.2.3
  'pako': 1.0.11
  'picocolors': 1.1.0
  'pinia': 2.1.7
  'postcss': 8.4.45
  'postcss-selector-parser': 6.1.2
  'qrcode-reader': 1.0.4
  'qrcode-terminal': 0.12.0
  'resolve': 1.22.8
  'rollup': 4.21.2
  'safe-area-insets': 1.4.1
  'source-map-js': 1.2.1
  'unimport': 4.1.1
  'unplugin-auto-import': 19.1.0
  'vite': 5.2.8
  'vue': 3.4.21
  'vue-i18n': 9.1.9
  'vue-router': 4.4.4
  'vuex': 4.1.0
  'ws': 8.18.0
  'xregexp': 3.1.0
