import { UniOAuthWeixinProvider } from '../interface.uts';
import { OauthWeixinFailImpl } from '../unierror.uts';
import WXAPIFactory from 'com.tencent.mm.opensdk.openapi.WXAPIFactory';
import IWXAPI from 'com.tencent.mm.opensdk.openapi.IWXAPI';
import SendAuth from 'com.tencent.mm.opensdk.modelmsg.SendAuth';
import BaseResp from 'com.tencent.mm.opensdk.modelbase.BaseResp';
import PackageManager from 'android.content.pm.PackageManager';

export class UniOAuthWeixinProviderImpl implements UniOAuthWeixinProvider {

    private appId : string = '';
    private api : IWXAPI | null = null;

    override id : string = "weixin";
    override description : string = "微信登录";
    override isWeChatInstalled : boolean = false;
    override isAppExist : boolean | null = false;

    constructor() {
        this.appId = this.getWXAppId();
        this.isWeChatInstalled = this.isInstalled();
        this.isAppExist = this.isWeChatInstalled;
        this.api = WXAPIFactory.createWXAPI(UTSAndroid.getAppContext(), this.appId);
        this.api?.registerApp(this.appId);
    }

    override login(options : LoginOptions) {
        if (this.appId.length == 0) {
            const err = new OauthWeixinFailImpl(1310500);
            options.fail?.(err);
            options.complete?.(err);
            return;
        }
        if (!this.isWeChatInstalled) {
            const err = new OauthWeixinFailImpl(1310502);
            options.fail?.(err);
            options.complete?.(err);
            return;
        }
        const req = new SendAuth.Req();
        req.scope = "snsapi_userinfo";
        req.state = "wechat_sdk_dcloud_weixin_oauth";
        const res = this.api?.sendReq(req) ?? false;
        if (res) {
            uni.$once('uni-oauth-weixin', (res : UTSJSONObject) => {
                switch (res.getNumber("errCode")) {
                    case BaseResp.ErrCode.ERR_OK:
                        let authResult : any | null = null;
                        if (!(options?.onlyAuthorize ?? false)) {
                            authResult = {
                              authResult: res.getBoolean("authResult", false),
                              code: res.getString("code", ""),
                              country: res.getString("country", ""),
                              lang: res.getString("lang", ""),
                              state: res.getString("state", ""),
                              url: res.getString("url", "")
                          };
                        }
                        const success = {
                            code: res.getString("code", ""),
                            authResult: authResult ?? {}
                        } as LoginSuccess;
                        options.success?.(success);
                        options.complete?.(success);
                        break;
                    case BaseResp.ErrCode.ERR_USER_CANCEL:
                        const fail1 = new OauthWeixinFailImpl(1310509);
                        options.fail?.(fail1);
                        options.complete?.(fail1);
                        break;
                    case BaseResp.ErrCode.ERR_AUTH_DENIED:
                        const fail2 = new OauthWeixinFailImpl(1310503);
                        options.fail?.(fail2);
                        options.complete?.(fail2);
                        break;
                    default:
                        break;
                }
            });
        } else {
            const err = new OauthWeixinFailImpl(1310507);
            options.fail?.(err);
            options.complete?.(err);
        }
    }

    override getUserInfo(options : GetUserInfoOptions) {
    }

    private getWXAppId() : string {
        const ctx = UTSAndroid.getAppContext();
        if (ctx == null) return '';
        const metaData = ctx.getPackageManager().getApplicationInfo(ctx.packageName, PackageManager.GET_META_DATA).metaData;
        return metaData.getString('WX_APPID', '');
    }

    private isInstalled() : boolean {
        return WXAPIFactory.createWXAPI(UTSAndroid.getAppContext(), this.appId).isWXAppInstalled();
    }
}