const { getManifestJson } = require('@dcloudio/uni-cli-shared/lib/manifest')

// UNI_INPUT_DIR 在 test 环境下不存在
const manifestJson = process.env.UNI_INPUT_DIR ? getManifestJson() : {}
const nativeTags = (manifestJson[process.env.UNI_PLATFORM] || {}).nativeTags || []
const tags = {
  // 小程序平台通用组件
  base: [
    'slot',
    'block',
    'component',
    'template',

    'ad',
    'audio',
    'button',
    'camera',
    'canvas',
    'checkbox',
    'checkbox-group',
    'cover-image',
    'cover-view',
    'form',
    'functional-page-navigator',
    'icon',
    'image',
    'input',
    'label',
    'live-player',
    'live-pusher',
    'map',
    'movable-area',
    'movable-view',
    'navigator',
    'official-account',
    'open-data',
    'picker',
    'picker-view',
    'picker-view-column',
    'progress',
    'radio',
    'radio-group',
    'rich-text',
    'scroll-view',
    'slider',
    'swiper',
    'swiper-item',
    'switch',
    'text',
    'textarea',
    'video',
    'view',
    'web-view',
    'editor'
  ],
  'mp-baidu': [
    'animation-video',
    'animation-view',
    'ar-camera',
    'rtc-room',
    'rtc-room-item',
    'tabs',
    'tab-item',
    'follow-swan',
    'login',
    'inline-payment-panel',
    'talos-linear-gradient',
    'talos-rc-view',
    'talos-nested-scroll-view',
    'talos-nested-scroll-top-container',
    'talos-nested-scroll-bottom-container',
    'talos-waterfall-view',
    'talos-waterfall-item',
    'talos-waterfall-header',
    'talos-waterfall-footer',
    'talos-pull-refresh',
    'talos-control-container',
    'talos-na-refresh-control',
    'talos-modal',
    'talos-svg',
    ...nativeTags
  ],
  'mp-weixin': [
    'page-container',
    'page-meta',
    'navigation-bar',
    'match-media',
    'share-element',
    'channel-live',
    'channel-video',
    'voip-room',
    'root-portal',
    'subscribe',
    // 手势组件
    'tap-gesture-handler',
    'double-tap-gesture-handler',
    'scale-gesture-handler',
    'force-press-gesture-handler',
    'pan-gesture-handler',
    'vertical-drag-gesture-handler',
    'horizontal-drag-gesture-handler',
    'long-press-gesture-handler',
    // 其他
    'draggable-sheet',
    'grid-builder',
    'grid-view',
    'list-view',
    'list-builder',
    'nested-scroll-body',
    'nested-scroll-header',
    'open-container',
    'official-account-publish',
    'share-element',
    'snapshot',
    // 'span', // todo: 临时移除 span 的支持，后续判断 skyline 环境进行区分 ask 190418
    'sticky-header',
    'sticky-section',
    'store-product',
    'store-home',
    'store-gift',
    'store-coupon',
    'open-data-list',
    'open-data-item',
    'selection',
    ...nativeTags
  ],
  // 支付宝小程序平台独有组件
  'mp-alipay': [
    'lifestyle',
    'life-follow',
    'contact-button',
    'spread',
    'error-view',
    'poster',
    'cashier',
    'ix-grid',
    'ix-native-grid',
    'ix-native-list',
    'mkt',
    'page-container',
    'page-meta',
    'root-portal',
    'share-element',
    'lottie',
    'join-group-chat',
    'subscribe-message',
    'mpass-component',
    ...nativeTags
  ],
  // 抖音小程序平台独有组件
  'mp-toutiao': [
    'draw-ad',
    'aweme-data',
    'consume-card',
    'pay-button',
    'rate-button',
    'member-button',
    'confirm-receipt-button',
    'live-preview',
    'aweme-live-book',
    'aweme-user-card',
    'rtc-room',
    'clue-order-form',
    'shop-follow-card',
    'mask',
    ...nativeTags
  ],
  'mp-kuaishou': [
    'follow-service',
    'payment-list',
    'playlet',
    'address',
    'page-meta',
    'navigation-bar',
    ...nativeTags
  ],
  'mp-xhs': ['post-note-button', 'group-chat-card', 'video-player', ...nativeTags],
  'mp-jd': ['root-portal', 'page-container', ...nativeTags],
  'mp-qq': [...nativeTags],
  'mp-harmony': [...nativeTags]
}

module.exports = {
  tags
}
