export const CHANGE_HOME_DATA = 'CHANGE_HOME_DATA'
export const STORE_ID_LIST = 'STORE_ID_LIST'

export const CHANGE_MOVIE_LIST = 'CHANGE_MOVIE_LIST'
export const CHANGE_CURRENT_MOVIE = 'CHANGE_CURRENT_MOVIE'

export const CHANGE_READ_LIST = 'CHANGE_READ_LIST'
export const CHANGE_CURRENT_READ = 'CHANGE_CURRENT_READ'

export const CHANGE_MUSIC_LIST = 'CHANGE_MUSIC_LIST'
export const CHANGE_CURRENT_MUSIC = 'CHANGE_CURRENT_MUSIC'

export const SET_LOCATION = 'SET_LOCATION'
export const SET_WEATHER = 'SET_WEATHER'
