import { SetScreenBrightness, SetScreenBrightnessOptions, SetScreenBrightnessSuccess, GetScreenBrightness, GetScreenBrightnessOptions, GetScreenBrightnessSuccess, SetKeepScreenOn, SetKeepScreenOnOptions, SetKeepScreenOnSuccess } from "../interface.uts"
import { API_SET_SCREEN_BRIGHTNESS, SetScreenBrightnessApiOptions, SetScreenBrightnessApiProtocol, API_GET_SCREEN_BRIGHTNESS, API_SET_KEEP_SCREEN_ON } from "../protocol.uts"
import harmonyWindow from '@ohos.window'
import { BusinessError } from '@kit.BasicServicesKit';
import { settings } from '@kit.BasicServicesKit';
import common from '@ohos.app.ability.common';

function normalizeBrightness(value : number) : number {
	if (value < 0) {
		return 0
	}
	if (value > 1) {
		return 1
	}
	return value
}

export const setScreenBrightness : SetScreenBrightness = defineAsyncApi<SetScreenBrightnessOptions, SetScreenBrightnessSuccess>(
	API_SET_SCREEN_BRIGHTNESS,
	(options : SetScreenBrightnessOptions, res : ApiExecutor<SetScreenBrightnessSuccess>) => {
		const windowStage : harmonyWindow.WindowStage = UTSHarmony.getWindowStage() as harmonyWindow.WindowStage
		windowStage.getMainWindow((err : BusinessError, window) => {
			const errCode : number = err.code;
			if (errCode) {
				res.reject(`setScreenBrightness:fail. code: ${err.code}, message: ${err.message}`);
				return;
			}
			let brightness : number = normalizeBrightness(options.value);
			try {
				window.setWindowBrightness(brightness, (err : BusinessError) => {
					const errCode : number = err.code;
					if (errCode) {
						res.reject(`setScreenBrightness:fail. code: ${err.code}, message: ${err.message}`);
						return;
					}
					res.resolve({} as SetScreenBrightnessSuccess)
				});
			} catch (exception) {
				res.reject(`setScreenBrightness:fail. code: ${exception.code}, message: ${exception.message}`);
			}
		});
	},
	SetScreenBrightnessApiProtocol,
	SetScreenBrightnessApiOptions
) as SetScreenBrightness


export const getScreenBrightness : GetScreenBrightness = defineAsyncApi<GetScreenBrightnessOptions, GetScreenBrightnessSuccess>(
	API_GET_SCREEN_BRIGHTNESS,
	(_ : GetScreenBrightnessOptions, res : ApiExecutor<GetScreenBrightnessSuccess>) => {
		const windowStage : harmonyWindow.WindowStage = UTSHarmony.getWindowStage() as harmonyWindow.WindowStage
		windowStage.getMainWindow((err : BusinessError, window) => {
			const errCode : number = err.code;
			if (errCode) {
				res.reject(`getScreenBrightness:fail. code: ${err.code}, message: ${err.message}`);
				return;
			}
			try {
				let brightness = window.getWindowProperties().brightness
				if (brightness == -1) {
					const context = UTSHarmony.getUIAbilityContext() as common.UIAbilityContext
					let value = Number(settings.getValueSync(context, settings.display.SCREEN_BRIGHTNESS_STATUS, '-1'));
					brightness = (!isNaN(value) && value >= 0) ? value / 255 : 1
				}
				res.resolve({
					value: normalizeBrightness(brightness)
				} as GetScreenBrightnessSuccess)
			} catch (exception) {
				res.reject(`getScreenBrightness:fail. code: ${exception.code}, message: ${exception.message}`);
			}
		});
	}
) as GetScreenBrightness


export const setKeepScreenOn : SetKeepScreenOn = defineAsyncApi<SetKeepScreenOnOptions, SetKeepScreenOnSuccess>(
	API_SET_KEEP_SCREEN_ON,
	(option : SetKeepScreenOnOptions, res : ApiExecutor<SetKeepScreenOnSuccess>) => {
		const windowStage : harmonyWindow.WindowStage = UTSHarmony.getWindowStage() as harmonyWindow.WindowStage
		windowStage.getMainWindow((err : BusinessError, window) => {
			const errCode : number = err.code;
			if (errCode) {
				res.reject(`setKeepScreenOn:fail. code: ${err.code}, message: ${err.message}`);
				return;
			}
			try {
				window.setWindowKeepScreenOn(option.keepScreenOn, (err : BusinessError) => {
					const errCode : number = err.code;
					if (errCode) {
						res.reject(`setKeepScreenOn:fail. code: ${err.code}, message: ${err.message}`);
						return;
					}
					res.resolve({
						errMsg: 'setKeepScreenOn:ok'
					} as SetKeepScreenOnSuccess)
				});
			} catch (exception) {
				res.reject(`setKeepScreenOn:fail. code: ${exception.code}, message: ${exception.message}`);
			}
		});
	}
) as SetKeepScreenOn

export {
    GetScreenBrightness,
    GetScreenBrightnessComplete,
    GetScreenBrightnessCompleteCallback,
    GetScreenBrightnessFail,
    GetScreenBrightnessFailCallback,
    GetScreenBrightnessOptions,
    GetScreenBrightnessSuccess,
    GetScreenBrightnessSuccessCallback,
    SetKeepScreenOn,
    SetKeepScreenOnComplete,
    SetKeepScreenOnCompleteCallback,
    SetKeepScreenOnFail,
    SetKeepScreenOnFailCallback,
    SetKeepScreenOnOptions,
    SetKeepScreenOnSuccess,
    SetKeepScreenOnSuccessCallback,
    SetScreenBrightness,
    SetScreenBrightnessComplete,
    SetScreenBrightnessCompleteCallback,
    SetScreenBrightnessFail,
    SetScreenBrightnessFailCallback,
    SetScreenBrightnessOptions,
    SetScreenBrightnessSuccess,
    SetScreenBrightnessSuccessCallback
} from "../interface.uts"
