import navigateTo from 'uni-helpers/navigate-to'
import redirectTo from '../../../mp-weixin/helpers/redirect-to'
import previewImage from '../../../mp-weixin/helpers/normalize-preview-image'
export const protocols = {
  navigateTo,
  redirectTo,
  previewImage
}
export const todos = [
  'preloadPage',
  'unPreloadPage',
  'loadSubPackage'
  // 'startBeaconDiscovery',
  // 'stopBeaconDiscovery',
  // 'getBeacons',
  // 'onBeaconUpdate',
  // 'onBeaconServiceChange',
  // 'addPhoneContact',
  // 'getHCEState',
  // 'startHCE',
  // 'stopHCE',
  // 'onHCEMessage',
  // 'sendHCEMessage',
  // 'startWifi',
  // 'stopWifi',
  // 'connectWifi',
  // 'getWifiList',
  // 'onGetWifiList',
  // 'setWifiList',
  // 'onWifiConnected',
  // 'getConnectedWifi',
  // 'setTopBarText',
  // 'getPhoneNumber',
  // 'chooseAddress',
  // 'addCard',
  // 'openCard',
  // 'getWeRunData',
  // 'launchApp',
  // 'chooseInvoiceTitle',
  // 'checkIsSupportSoterAuthentication',
  // 'startSoterAuthentication',
  // 'checkIsSoterEnrolledInDevice',
  // 'vibrate',
  // 'loadFontFace',
  // 'getExtConfig',
  // 'getExtConfigSync'
]
export const canIUses = [
  'scanCode',
  'startAccelerometer',
  'stopAccelerometer',
  'onAccelerometerChange',
  'startCompass',
  'onCompassChange',
  'setScreenBrightness',
  'getScreenBrightness',
  'setKeepScreenOn',
  'onUserCaptureScreen',
  'vibrateLong',
  'vibrateShort',
  'createWorker',
  'connectSocket',
  'onSocketOpen',
  'onSocketError',
  'sendSocketMessage',
  'onSocketMessage',
  'closeSocket',
  'onSocketClose',
  'openDocument',
  'updateShareMenu',
  'getShareInfo',
  'createLivePlayerContext',
  'createLivePusherContext',
  'setNavigationBarColor',
  'onMemoryWarning',
  'onNetworkStatusChange',
  'reportMonitor',
  'getLogManager',
  'reportAnalytics'
]
