/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
export {}

declare module 'vue' {
  export interface GlobalComponents {
    test: typeof import('./components/test/test.uvue')['default']
    'test-a': typeof import('./components/test-a/test-a.vue')['default']
    'test-b': typeof import('./uni_modules/test-easycom/components/test-b/test-b.vue')['default']
    'uni-badge': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue')['default']
    'uni-breadcrumb': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-breadcrumb/uni-breadcrumb.vue')['default']
    'uni-breadcrumb-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-breadcrumb-item/uni-breadcrumb-item.vue')['default']
    'uni-calendar': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-calendar/uni-calendar.vue')['default']
    'uni-calendar-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-calendar/uni-calendar-item.vue')['default']
    'uni-card': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-card/uni-card.vue')['default']
    'uni-col': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-col/uni-col.vue')['default']
    'uni-collapse': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-collapse/uni-collapse.vue')['default']
    'uni-collapse-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-collapse-item/uni-collapse-item.vue')['default']
    'uni-combox': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-combox/uni-combox.vue')['default']
    'uni-countdown': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-countdown/uni-countdown.vue')['default']
    'uni-data-checkbox': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-data-checkbox/uni-data-checkbox.vue')['default']
    'uni-data-picker': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-data-picker/uni-data-picker.vue')['default']
    'uni-data-pickerview': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-data-pickerview/uni-data-pickerview.vue')['default']
    'uni-data-select': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-data-select/uni-data-select.vue')['default']
    'uni-dateformat': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-dateformat/uni-dateformat.vue')['default']
    'uni-datetime-picker': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-datetime-picker/uni-datetime-picker.vue')['default']
    'uni-drawer': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-drawer/uni-drawer.vue')['default']
    'uni-easyinput': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-easyinput/uni-easyinput.vue')['default']
    'uni-fab': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-fab/uni-fab.vue')['default']
    'uni-fav': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-fav/uni-fav.vue')['default']
    'uni-file-picker': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-file-picker/uni-file-picker.vue')['default']
    'uni-forms': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-forms/uni-forms.vue')['default']
    'uni-forms-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-forms-item/uni-forms-item.vue')['default']
    'uni-goods-nav': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-goods-nav/uni-goods-nav.vue')['default']
    'uni-grid': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-grid/uni-grid.vue')['default']
    'uni-grid-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-grid-item/uni-grid-item.vue')['default']
    'uni-group': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-group/uni-group.vue')['default']
    'uni-icons': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue')['default']
    'uni-indexed-list': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-indexed-list/uni-indexed-list.vue')['default']
    'uni-indexed-list-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-indexed-list/uni-indexed-list-item.vue')['default']
    'uni-link': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-link/uni-link.vue')['default']
    'uni-list': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-list/uni-list.vue')['default']
    'uni-list-ad': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-list-ad/uni-list-ad.vue')['default']
    'uni-list-chat': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-list-chat/uni-list-chat.vue')['default']
    'uni-list-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-list-item/uni-list-item.vue')['default']
    'uni-load-more': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue')['default']
    'uni-nav-bar': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-nav-bar/uni-nav-bar.vue')['default']
    'uni-notice-bar': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-notice-bar/uni-notice-bar.vue')['default']
    'uni-number-box': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-number-box/uni-number-box.vue')['default']
    'uni-pagination': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-pagination/uni-pagination.vue')['default']
    'uni-popup': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-popup/uni-popup.vue')['default']
    'uni-popup-dialog': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-popup-dialog/uni-popup-dialog.vue')['default']
    'uni-popup-message': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-popup-message/uni-popup-message.vue')['default']
    'uni-popup-share': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-popup-share/uni-popup-share.vue')['default']
    'uni-rate': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-rate/uni-rate.vue')['default']
    'uni-refresh': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-list/uni-refresh.vue')['default']
    'uni-row': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-row/uni-row.vue')['default']
    'uni-search-bar': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-search-bar/uni-search-bar.vue')['default']
    'uni-section': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-section/uni-section.vue')['default']
    'uni-segmented-control': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-segmented-control/uni-segmented-control.vue')['default']
    'uni-status-bar': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-nav-bar/uni-status-bar.vue')['default']
    'uni-steps': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-steps/uni-steps.vue')['default']
    'uni-swipe-action': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.vue')['default']
    'uni-swipe-action-item': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-swipe-action-item/uni-swipe-action-item.vue')['default']
    'uni-swiper-dot': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-swiper-dot/uni-swiper-dot.vue')['default']
    'uni-table': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-table/uni-table.vue')['default']
    'uni-tag': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-tag/uni-tag.vue')['default']
    'uni-tbody': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-tbody/uni-tbody.vue')['default']
    'uni-td': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-td/uni-td.vue')['default']
    'uni-th': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-th/uni-th.vue')['default']
    'uni-thead': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-thead/uni-thead.vue')['default']
    'uni-title': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-title/uni-title.vue')['default']
    'uni-tooltip': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-tooltip/uni-tooltip.vue')['default']
    'uni-tr': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-tr/uni-tr.vue')['default']
    'uni-transition': typeof import('./node_modules/@dcloudio/uni-ui/lib/uni-transition/uni-transition.vue')['default']
  }
}
