// This file is automatically generated.
// Do not modify this file -- YOUR CHANGES WILL BE ERASED!
// @ts-expect-error
import { UniMatchMediaElement } from '@dcloudio/uni-ext-api/uni-match-media/customElements/uni-match-media/uni-match-media.uts.ts'
export const MatchMedia = /*#__PURE__*/ (() => {
  // @ts-expect-error
  customElements.define('uni-match-media', UniMatchMediaElement)
  return 'uni-match-media'
})()
