import { PageScrollToOptions, PageScrollToSuccess } from '../interface.uts'
import { PageScrollToFailImpl } from '../unierror.uts'
function queryElementTop(
    component: ComponentPublicInstance,
    selector: string,
): number | null {
    let scrollNode = component.$el?.querySelector(selector)
    if (scrollNode != null) {
        return scrollNode.getBoundingClientRect().top
    }
    return null
}

export const pageScrollTo = defineAsyncApi<
    PageScrollToOptions,
    PageScrollToSuccess
>('pageScrollTo', (options: PageScrollToOptions, res: ApiExecutor) => {
    const pages = getCurrentPages()
    const currentPage = pages[pages.length - 1]
    if(currentPage == null) {
        res.reject(new PageScrollToFailImpl('current page not found'))
        return
    }
    const scrollViewNode = currentPage.vm?.$el
    if (scrollViewNode == null || scrollViewNode.tagName != 'SCROLL-VIEW') {
        res.reject(new PageScrollToFailImpl('selector invalid'))
        return
    }

    let top = options.scrollTop
    if (options.selector != null) {
        top = queryElementTop(currentPage.vm!, options.selector!)
        if (top != null) {
            const currentScrollTop = scrollViewNode.getAnyAttribute(
                'scrollTop',
            ) as number
            top += currentScrollTop
        }
    }

    if (top == null || top < 0) {
        res.reject(new PageScrollToFailImpl('top or selector invalid'))
        return
    }

    if (options.offsetTop != null) {
        top += options.offsetTop!
    }

    scrollViewNode.setAnyAttribute('scrollTop', top)
    res.resolve(null)
})
