export const styles = {
  ['uni-switch']: {
    'flex-direction': 'row',
    'align-items': 'center',
    'overflow-x': 'visible',
    'overflow-y': 'visible',
  },
  ['uni-switch-input']: {
    'box-sizing': 'border-box',
    position: 'relative',
    'flex-direction': 'row',
    'background-color': 'rgb(229, 229, 229)',
    'border-top-width': '2px',
    'border-right-width': '2px',
    'border-bottom-width': '2px',
    'border-left-width': '2px',
    'border-top-style': 'solid',
    'border-right-style': 'solid',
    'border-bottom-style': 'solid',
    'border-left-style': 'solid',
    'border-top-color': 'rgb(229, 229, 229)',
    'border-right-color': 'rgb(229, 229, 229)',
    'border-bottom-color': 'rgb(229, 229, 229)',
    'border-left-color': 'rgb(229, 229, 229)',
    'border-image-source': 'initial',
    'border-image-slice': 'initial',
    'border-image-width': 'initial',
    'border-image-outset': 'initial',
    'border-image-repeat': 'initial',
    'border-top-left-radius': '16px',
    'border-top-right-radius': '16px',
    'border-bottom-right-radius': '16px',
    'border-bottom-left-radius': '16px',
    width: '52px',
    height: '32px',
    'transition-duration': '0.1s',
    'transition-property': 'background-color, border-color',
    'overflow-x': 'visible',
    'overflow-y': 'visible',
  },
  ['uni-switch-thumb']: {
    width: '28px',
    height: '28px',
    'background-color': 'rgb(255, 255, 255)',
    'border-top-left-radius': '15px',
    'border-top-right-radius': '15px',
    'border-bottom-right-radius': '15px',
    'border-bottom-left-radius': '15px',
    'transition-duration': '0.3s',
    'transition-property': 'transform',
    transform: 'translateX(0px)',
    'overflow-x': 'visible',
    'overflow-y': 'visible',
  },
  ['uni-switch-thumb-checked']: {
    transform: 'translateX(20px)',
  },
  ['uni-switch-disabled']: {
    opacity: '0.7',
  },
}
