// This file is auto-generated by the build process. Do not edit manually.

export const UVUE_VAPOR_APP_ANDROID_CUSTOM_ELEMENTS: string[] = []

export const UVUE_VAPOR_APP_ANDROID_COMPONENTS: string[] = []

export const UVUE_VAPOR_APP_ANDROID_EASYCOMS = [
  'ad',
  'camera',
  'canvas',
  'editor',
  'button',
  'checkbox',
  'checkbox-group',
  'form',
  'input',
  'label',
  'picker',
  'picker-view',
  'picker-view-column',
  'radio',
  'radio-group',
  'slider',
  'switch',
  'textarea',
  'list-item',
  'list-view',
  'sticky-header',
  'sticky-section',
  'live-player',
  'live-pusher',
  'loading',
  'map',
  'match-media',
  'navigator',
  'page-container',
  'progress',
  'rich-text',
  'swiper',
  'swiper-item',
  'video',
  'flow-item',
  'waterflow',
  'web-view',
]

export const UVUE_VAPOR_APP_IOS_CUSTOM_ELEMENTS: string[] = []

export const UVUE_VAPOR_APP_IOS_COMPONENTS: string[] = []

export const UVUE_VAPOR_APP_IOS_EASYCOMS = [
  'ad',
  'camera',
  'canvas',
  'editor',
  'button',
  'checkbox',
  'checkbox-group',
  'form',
  'input',
  'label',
  'picker',
  'picker-view',
  'picker-view-column',
  'radio',
  'radio-group',
  'slider',
  'switch',
  'textarea',
  'list-item',
  'list-view',
  'sticky-header',
  'sticky-section',
  'live-player',
  'live-pusher',
  'loading',
  'map',
  'match-media',
  'navigator',
  'page-container',
  'progress',
  'rich-text',
  'swiper',
  'swiper-item',
  'video',
  'flow-item',
  'waterflow',
  'web-view',
]

export const UVUE_VAPOR_APP_HARMONY_CUSTOM_ELEMENTS: string[] = []

export const UVUE_VAPOR_APP_HARMONY_COMPONENTS: string[] = []

export const UVUE_VAPOR_APP_HARMONY_EASYCOMS = [
  'canvas',
  'editor',
  'button',
  'checkbox',
  'checkbox-group',
  'form',
  'input',
  'label',
  'picker',
  'picker-view',
  'picker-view-column',
  'radio',
  'radio-group',
  'slider',
  'switch',
  'textarea',
  'list-item',
  'list-view',
  'sticky-header',
  'sticky-section',
  'loading',
  'map',
  'match-media',
  'navigator',
  'page-container',
  'progress',
  'rich-text',
  'swiper',
  'swiper-item',
  'video',
  'flow-item',
  'waterflow',
  'web-view',
]

export const UVUE_VAPOR_APP_CUSTOM_ELEMENTS: string[] = []

export const UVUE_VAPOR_APP_COMPONENTS: string[] = []

export const UVUE_VAPOR_APP_EASYCOMS = [
  'ad',
  'camera',
  'canvas',
  'editor',
  'button',
  'checkbox',
  'checkbox-group',
  'form',
  'input',
  'label',
  'picker',
  'picker-view',
  'picker-view-column',
  'radio',
  'radio-group',
  'slider',
  'switch',
  'textarea',
  'list-item',
  'list-view',
  'sticky-header',
  'sticky-section',
  'live-player',
  'live-pusher',
  'loading',
  'map',
  'match-media',
  'navigator',
  'page-container',
  'progress',
  'rich-text',
  'swiper',
  'swiper-item',
  'video',
  'flow-item',
  'waterflow',
  'web-view',
]

export const UVUE_APP_ANDROID_CUSTOM_ELEMENTS = ['match-media']

export const UVUE_APP_ANDROID_COMPONENTS = ['ad']

export const UVUE_APP_ANDROID_EASYCOMS = [
  'camera',
  'editor',
  'live-player',
  'live-pusher',
  'loading',
  'map',
  'picker',
  'rich-text',
  'video',
  'web-view',
]

export const UVUE_APP_IOS_CUSTOM_ELEMENTS = [
  'checkbox',
  'checkbox-group',
  'form',
  'picker-view',
  'picker-view-column',
  'radio',
  'radio-group',
  'switch',
  'progress',
]

export const UVUE_APP_IOS_COMPONENTS = ['ad']

export const UVUE_APP_IOS_EASYCOMS = [
  'camera',
  'editor',
  'live-player',
  'live-pusher',
  'loading',
  'map',
  'match-media',
  'page-container',
  'picker',
  'rich-text',
  'video',
  'web-view',
]

export const UVUE_APP_HARMONY_CUSTOM_ELEMENTS = [
  'canvas',
  'button',
  'checkbox',
  'checkbox-group',
  'form',
  'label',
  'picker-view',
  'picker-view-column',
  'radio',
  'radio-group',
  'slider',
  'switch',
  'match-media',
  'navigator',
  'picker',
  'progress',
]

export const UVUE_APP_HARMONY_COMPONENTS: string[] = []

export const UVUE_APP_HARMONY_EASYCOMS = [
  'editor',
  'loading',
  'map',
  'page-container',
  'rich-text',
  'video',
]

export const UVUE_APP_CUSTOM_ELEMENTS = [
  'match-media',
  'checkbox',
  'checkbox-group',
  'form',
  'picker-view',
  'picker-view-column',
  'radio',
  'radio-group',
  'switch',
  'progress',
  'canvas',
  'button',
  'label',
  'slider',
  'navigator',
  'picker',
]

export const UVUE_APP_COMPONENTS = ['ad']

export const UVUE_APP_EASYCOMS = [
  'camera',
  'editor',
  'live-player',
  'live-pusher',
  'loading',
  'map',
  'picker',
  'rich-text',
  'video',
  'web-view',
  'match-media',
  'page-container',
]
