
export type SocketDataOptions =
	/**
	 * @description 字符串
	 * @uniPlatform {
	 *    "app": {
	 *        "android": {
	 *  		  "uniVer": "√",
	 * 			  "unixVer": "x"
	 *        },
	 *        "ios": {
	 *  		  "uniVer": "√",
	 * 			  "unixVer": "x"
	 *        }
	 *    }
	 * }
	 */
	String
	/**
	 * @description ArrayBuffer
	 * @uniPlatform {
	 *    "app": {
	 *        "android": {
	 *  		  "uniVer": "√",
	 * 			  "unixVer": "x"
	 *        },
	 *        "ios": {
	 *  		  "uniVer": "√",
	 * 			  "unixVer": "x"
	 *        }
	 *    }
	 * }
	 */
	| ArrayBuffer;
