import {
    API_EXIT
} from '../protocol.uts'
import {
    Exit
} from '../interface.uts'

export const exit: Exit = defineSyncApi<void>(
    API_EXIT,
    function () {
        UTSHarmony.exit()
    }
) as Exit
export {
    Exit,
    ExitCompleteCallback,
    ExitErrorCode,
    ExitFail,
    ExitFailCallback,
    ExitOptions,
    ExitSuccess,
    ExitSuccessCallback,
    IExitError
} from '../interface.uts';