import { Share, ShareOptions, UniShareProvider, ShareProvider } from "../interface.uts";
import { ShareFailImpl } from "../unierror.uts";
import { UTSiOS } from "DCloudUTSFoundation";

const DEFAULT_PROVIDER : ShareProvider = 'weixin'

export const share : Share = function (options : ShareOptions) {
	
	const resolvedProvider = (options.provider == null || options.provider!.length == 0)
		? DEFAULT_PROVIDER
		: options.provider!;

	const provider = UTSiOS.getProvider<UniShareProvider>("share", resolvedProvider, UniShareProvider.self);
	if (provider != null) {
		provider!.share(options);
	} else {
		const err = new ShareFailImpl(4000600);
		options.fail?.(err);
		options.complete?.(err);
	}
};
