import {
  type ComponentInternalInstance as ComponentInternalInstanceOrigin,
  type ComponentPublicInstance as ComponentPublicInstanceOrigin,
  type CreateVueAppComponent as CreateVueAppComponentOrigin,
  type CreateVueComponent as CreateVueComponentOrigin,
  type DebuggerEvent as DebuggerEventOrigin,
  type DirectiveBinding as DirectiveBindingOrigin,
  type Directive as DirectiveOrigin,
  type Directive as DirectiveOrigin,
  type EffectScope as EffectScopeOrigin,
  type OnCleanup as OnCleanupOrigin,
  type PropType as PropTypeOrigin,
  type ReactiveEffect as ReactiveEffectOrigin,
  type Ref as RefOrigin,
  type RenderHelpers as RenderHelpersOrigin,
  type SlotsType as SlotsTypeOrigin,
  type VNode as VNodeOrigin,
  type VueAppComponent as VueAppComponentOrigin,
  type VueAppConfig as VueAppConfigOrigin,
  type VueAppContext as VueAppContextOrigin,
  type VueApp as VueAppOrigin,
  type VueComponentOptions as VueComponentOptionsOrigin,
  type VueComponent as VueComponentOrigin,
  type WatchEffect as WatchEffectOrigin,
  type WatchOptions as WatchOptionsOrigin,
  type WritableComputedOptions as WritableComputedOptionsOrigin,
  type cloneVNode as cloneVNodeOrigin,
  type computed as computedOrigin,
  type createAppContext as createAppContextOrigin,
  type createApp as createAppOrigin,
  type createCommentVNode as createCommentVNodeOrigin,
  type createElementVNode as createElementVNodeOrigin,
  type createSSRApp as createSSRAppOrigin,
  type createVNode as createVNodeOrigin,
  type currentInstance as currentInstanceOrigin,
  type customRef as customRefOrigin,
  type defineComponent as defineComponentOrigin,
  type defineMixin as defineMixinOrigin,
  type defineModel as defineModelOrigin,
  type defineOptions as defineOptionsOrigin,
  type definePlugin as definePluginOrigin,
  type effect as effectOrigin,
  effectScope as effectScopeOrigin,
  type getComponentName as getComponentNameOrigin,
  type getCurrentInstance as getCurrentInstanceOrigin,
  getCurrentScope as getCurrentScopeOrigin,
  type guardReactiveProps as guardReactivePropsOrigin,
  type h as hOrigin,
  type hasInjectionContext as hasInjectionContextOrigin,
  type injectHook as injectHookOrigin,
  type injectHookWithArg as injectHookWithArgOrigin,
  type inject as injectOrigin,
  type isMemoSame as isMemoSameOrigin,
  type isProxy as isProxyOrigin,
  type isReactive as isReactiveOrigin,
  type isReadonly as isReadonlyOrigin,
  type isRef as isRefOrigin,
  type isVNode as isVNodeOrigin,
  type isVNode as isVNodeOrigin,
  type markRaw as markRawOrigin,
  type mergeProps as mergePropsOrigin,
  type nextTick as nextTickOrigin,
  type normalizeCssStyles as normalizeCssStylesOrigin,
  type normalizePropsOptions as normalizePropsOptionsOrigin,
  type onActivated as onActivatedOrigin,
  type onBeforeCreate as onBeforeCreateOrigin,
  type onBeforeMount as onBeforeMountOrigin,
  type onBeforeUnmount as onBeforeUnmountOrigin,
  type onBeforeUpdate as onBeforeUpdateOrigin,
  type onCreated as onCreatedOrigin,
  type onDeactivated as onDeactivatedOrigin,
  type onErrorCaptured as onErrorCapturedOrigin,
  type onMounted as onMountedOrigin,
  type onRenderTracked as onRenderTrackedOrigin,
  type onRenderTriggered as onRenderTriggeredOrigin,
  onScopeDispose as onScopeDisposeOrigin,
  type onServerPrefetch as onServerPrefetchOrigin,
  type onUnmounted as onUnmountedOrigin,
  type onUpdated as onUpdatedOrigin,
  type padStyleMapOf as padStyleMapOfOrigin,
  type provide as provideOrigin,
  type queuePostFlushCb as queuePostFlushCbOrigin,
  type reactive as reactiveOrigin,
  type readonly as readonlyOrigin,
  type ref as refOrigin,
  type render as renderOrigin,
  type renderSlot as renderSlotOrigin,
  type resolveCache as resolveCacheOrigin,
  type resolveComponent as resolveComponentOrigin,
  type resolveComponent as resolveComponentOrigin,
  type resolveDirective as resolveDirectiveOrigin,
  type resolveDynamicComponent as resolveDynamicComponentOrigin,
  type resolveEasyComponent as resolveEasyComponentOrigin,
  type shallowReactive as shallowReactiveOrigin,
  type shallowReadonly as shallowReadonlyOrigin,
  type shallowRef as shallowRefOrigin,
  type stop as stopOrigin,
  type toDisplayString as toDisplayStringOrigin,
  type toHandlers as toHandlersOrigin,
  type toRaw as toRawOrigin,
  type toRef as toRefOrigin,
  type toRefs as toRefsOrigin,
  type toValue as toValueOrigin,
  type triggerRef as triggerRefOrigin,
  type unref as unrefOrigin,
  type useAttrs as useAttrsOrigin,
  type useModel as useModelOrigin,
  type useSlots as useSlotsOrigin,
  type vModelDynamic as vModelDynamicOrigin,
  type vShow as vShowOrigin,
  type watchEffect as watchEffectOrigin,
  type watch as watchOrigin,
  type watchPostEffect as watchPostEffectOrigin,
  type watchSyncEffect as watchSyncEffectOrigin,
  type withCtx as withCtxOrigin,
  type withDefaults as withDefaultsOrigin,
  type withDirectives as withDirectivesOrigin,
  type withDirectives as withDirectivesOrigin,
  type withMemo as withMemoOrigin,
  type withModifiers as withModifiersOrigin,
  type withModifiers as withModifiersOrigin,
} from '@vue/runtime-core'

declare global {
  const VueAppContext: typeof VueAppContextOrigin
  type VueAppContext = VueAppContextOrigin
  const createAppContext: typeof createAppContextOrigin
  const VueAppConfig: typeof VueAppConfigOrigin
  type VueAppConfig = VueAppConfigOrigin
  const VueApp: typeof VueAppOrigin
  type VueApp = VueAppOrigin
  const definePlugin: typeof definePluginOrigin
  const defineMixin: typeof defineMixinOrigin
  const defineComponent: typeof defineComponentOrigin
  const defineModel: typeof defineModelOrigin
  const defineOptions: typeof defineOptionsOrigin
  const createApp: typeof createAppOrigin
  const createSSRApp: typeof createSSRAppOrigin
  const withDirectives: typeof withDirectivesOrigin
  const VNode: typeof VNodeOrigin
  type VNode = VNodeOrigin
  const guardReactiveProps: typeof guardReactivePropsOrigin
  const createVNode: typeof createVNodeOrigin
  const createElementVNode: typeof createElementVNodeOrigin
  const createCommentVNode: typeof createCommentVNodeOrigin
  const isVNode: typeof isVNodeOrigin
  const nextTick: typeof nextTickOrigin
  const queuePostFlushCb: typeof queuePostFlushCbOrigin
  const watchEffect: typeof watchEffectOrigin
  const watchPostEffect: typeof watchPostEffectOrigin
  const watchSyncEffect: typeof watchSyncEffectOrigin
  const watch: typeof watchOrigin
  const provide: typeof provideOrigin
  const inject: typeof injectOrigin
  const currentInstance: typeof currentInstanceOrigin
  const getCurrentInstance: typeof getCurrentInstanceOrigin
  const CreateVueComponent: typeof CreateVueComponentOrigin
  type CreateVueComponent = CreateVueComponentOrigin
  const CreateVueAppComponent: typeof CreateVueAppComponentOrigin
  type CreateVueAppComponent = CreateVueAppComponentOrigin
  const VueAppComponent: typeof VueAppComponentOrigin
  type VueAppComponent = VueAppComponentOrigin
  const VueComponent: typeof VueComponentOrigin
  type VueComponent = VueComponentOrigin
  const ComponentInternalInstance: typeof ComponentInternalInstanceOrigin
  type ComponentInternalInstance = ComponentInternalInstanceOrigin
  const getComponentName: typeof getComponentNameOrigin
  const withCtx: typeof withCtxOrigin
  const render: typeof renderOrigin
  const h: typeof hOrigin
  const padStyleMapOf: typeof padStyleMapOfOrigin
  const normalizeCssStyles: typeof normalizeCssStylesOrigin
  const injectHook: typeof injectHookOrigin
  const injectHookWithArg: typeof injectHookWithArgOrigin
  const onBeforeCreate: typeof onBeforeCreateOrigin
  const onCreated: typeof onCreatedOrigin
  const onBeforeMount: typeof onBeforeMountOrigin
  const onMounted: typeof onMountedOrigin
  const onBeforeUpdate: typeof onBeforeUpdateOrigin
  const onUpdated: typeof onUpdatedOrigin
  const onBeforeUnmount: typeof onBeforeUnmountOrigin
  const onUnmounted: typeof onUnmountedOrigin
  const onErrorCaptured: typeof onErrorCapturedOrigin
  const onRenderTracked: typeof onRenderTrackedOrigin
  const onRenderTriggered: typeof onRenderTriggeredOrigin
  const onActivated: typeof onActivatedOrigin
  const onDeactivated: typeof onDeactivatedOrigin
  const onServerPrefetch: typeof onServerPrefetchOrigin
  const vShow: typeof vShowOrigin
  const vModelDynamic: typeof vModelDynamicOrigin
  const withModifiers: typeof withModifiersOrigin
  const RenderHelpers: typeof RenderHelpersOrigin
  type RenderHelpers = RenderHelpersOrigin
  type Directive = DirectiveOrigin
  type DirectiveBinding = DirectiveBindingOrigin
  const resolveComponent: typeof resolveComponentOrigin
  const resolveEasyComponent: typeof resolveEasyComponentOrigin
  const resolveDynamicComponent: typeof resolveDynamicComponentOrigin
  const toHandlers: typeof toHandlersOrigin
  const renderSlot: typeof renderSlotOrigin
  const withMemo: typeof withMemoOrigin
  const isMemoSame: typeof isMemoSameOrigin
  const resolveCache: typeof resolveCacheOrigin
  const normalizePropsOptions: typeof normalizePropsOptionsOrigin
  const toDisplayString: typeof toDisplayStringOrigin
  type Directive = DirectiveOrigin
  type WatchOptions = WatchOptionsOrigin
  type VueComponentOptions = VueComponentOptionsOrigin
  type ComponentPublicInstance = ComponentPublicInstanceOrigin
  type EffectScope = EffectScopeOrigin
  const EffectScope: typeof EffectScopeOrigin
  const ReactiveEffect: typeof ReactiveEffectOrigin
  type WritableComputedOptions<T> = WritableComputedOptionsOrigin<T>
  const computed: typeof computedOrigin
  const effect: typeof effectOrigin
  const effectScope = effectScopeOrigin
  const getCurrentScope = getCurrentScopeOrigin
  const onScopeDispose = onScopeDisposeOrigin
  type WatchEffect = WatchEffectOrigin
  type Ref<T> = RefOrigin<T>
  const isReactive: typeof isReactiveOrigin
  const isReadonly: typeof isReadonlyOrigin
  const isRef: typeof isRefOrigin
  const reactive: typeof reactiveOrigin
  const ref: typeof refOrigin
  const toRef: typeof toRefOrigin
  const toRefs: typeof toRefsOrigin
  const toValue: typeof toValueOrigin
  const triggerRef: typeof triggerRefOrigin
  const readonly: typeof readonlyOrigin
  const shallowReactive: typeof shallowReactiveOrigin
  const shallowRef: typeof shallowRefOrigin
  const shallowReadonly: typeof shallowReadonlyOrigin
  const stop: typeof stopOrigin
  const toRaw: typeof toRawOrigin
  const markRaw: typeof markRawOrigin
  const unref: typeof unrefOrigin
  const customRef: typeof customRefOrigin
  const isProxy: typeof isProxyOrigin
  type PropType<T> = PropTypeOrigin<T>
  type SlotsType<T> = SlotsTypeOrigin<T>
  type DebuggerEvent = DebuggerEventOrigin
  type OnCleanup = OnCleanupOrigin
  const withDefaults: typeof withDefaultsOrigin
  const useSlots: typeof useSlotsOrigin
  const useAttrs: typeof useAttrsOrigin
  const useModel: typeof useModelOrigin
  const hasInjectionContext: typeof hasInjectionContextOrigin
  const mergeProps: typeof mergePropsOrigin
  const cloneVNode: typeof cloneVNodeOrigin
  const isVNode: typeof isVNodeOrigin
  const resolveComponent: typeof resolveComponentOrigin
  const resolveDirective: typeof resolveDirectiveOrigin
  const withModifiers: typeof withModifiersOrigin
  const withDirectives: typeof withDirectivesOrigin
}
