/// <reference types="google.maps" />
export type GoogleMaps = typeof google.maps
export type OverlayView = google.maps.OverlayView
export type LatLng = google.maps.LatLng
export type Polyline = google.maps.Polyline
export type PolylineOptions = google.maps.PolylineOptions
export type Map = google.maps.Map
export type Marker = google.maps.Marker
export type Label = google.maps.MarkerLabel
export type Circle = google.maps.Circle
export type Icon = google.maps.Icon
export type Polygon = google.maps.Polygon
export type PolygonOptions = google.maps.PolygonOptions
export type CircleOptions = google.maps.CircleOptions
