import '../uts/index.d.ts'
import './hbuilder-x/index.d.ts'
import './vue.d.ts'
import './shims/common.d.ts'
import './shims/app-android.d.ts'
import '@uni-x/app-android.d.ts'
import '@dcloudio/uni-app-x/index.d.ts'
